/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserStadsRouteImport } from './routes/user-stads'
import { Route as UserRouteImport } from './routes/user'
import { Route as TestRouteImport } from './routes/test'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'

const UserStadsRoute = UserStadsRouteImport.update({
  id: '/user-stads',
  path: '/user-stads',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/summary': typeof SummaryRoute
  '/test': typeof TestRoute
  '/user': typeof UserRoute
  '/user-stads': typeof UserStadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/summary': typeof SummaryRoute
  '/test': typeof TestRoute
  '/user': typeof UserRoute
  '/user-stads': typeof UserStadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/summary': typeof SummaryRoute
  '/test': typeof TestRoute
  '/user': typeof UserRoute
  '/user-stads': typeof UserStadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/leaderboard'
    | '/login'
    | '/summary'
    | '/test'
    | '/user'
    | '/user-stads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/leaderboard'
    | '/login'
    | '/summary'
    | '/test'
    | '/user'
    | '/user-stads'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/leaderboard'
    | '/login'
    | '/summary'
    | '/test'
    | '/user'
    | '/user-stads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  SummaryRoute: typeof SummaryRoute
  TestRoute: typeof TestRoute
  UserRoute: typeof UserRoute
  UserStadsRoute: typeof UserStadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-stads': {
      id: '/user-stads'
      path: '/user-stads'
      fullPath: '/user-stads'
      preLoaderRoute: typeof UserStadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  SummaryRoute: SummaryRoute,
  TestRoute: TestRoute,
  UserRoute: UserRoute,
  UserStadsRoute: UserStadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
