networks:
  app-network-public:
    driver: bridge
name: gambling-problem-db
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      - app-network-public
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: "127.0.0.1"
      MYSQL_PORT: "3306"
    ports:
      - "${MYSQL_HOST}:${MYSQL_PORT}:3306"
    volumes:
      - ${PWD}/data/mysql:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: cache-redis
    ports:
      - "6379:6379"
    networks:
      - app-network-public
