-- GENERATED BY AI

USE gambling-problem;
SET @dummy_password_hash = '$argon2id$v=19$m=65536,t=3,p=4$cTQwF5uHH3L+yRI5JQHnLQ$HmiZPrG39xBodh5n5Muu2f4c5/uw1DNjQC33GACh/2o';

-- =====================================================
-- USERS (50)
-- =====================================================

INSERT INTO Users (userUuid, username, password)
WITH RECURSIVE seq AS (
    SELECT 1 AS n
    UNION ALL
    SELECT n + 1
    FROM seq
    WHERE n < 100
)
SELECT
    CONCAT('00000000-0000-0000-0000-', LPAD(n, 12, '0')),
    CONCAT('dummy_user_', LPAD(n, 3, '0')), -- optional: 001..100
    @dummy_password_hash
FROM seq;

-- =====================================================
-- RUNS
-- Metadata and Running are automatically created
-- by your triggers.
-- =====================================================

-- RUNS (100)

INSERT INTO Runs
(
    userUuid,
    moneyTotal,
    moneySpend,
    isRunning
)
WITH RECURSIVE seq AS (
    SELECT 1 AS n
    UNION ALL
    SELECT n + 1
    FROM seq
    WHERE n < 100
)
SELECT
    CONCAT('00000000-0000-0000-0000-', LPAD(n, 12, '0')),
    1000 + (n * 500),
    100 + (n * 50),
    CASE
        WHEN n <= 20 THEN TRUE  -- 20 active runs instead of 10
        ELSE FALSE
    END
FROM seq;

-- =====================================================
-- UPDATE AUTO-CREATED METADATA
-- =====================================================

UPDATE Metadata m
JOIN Runs r ON r.metadataID = m.metadataID
SET
    m.typeEnd = CASE
        WHEN r.isRunning = TRUE THEN NULL
        WHEN MOD(r.runId,4)=0 THEN 'WIN'
        WHEN MOD(r.runId,4)=1 THEN 'BANKRUPT'
        WHEN MOD(r.runId,4)=2 THEN 'TERMINATED'
        ELSE 'DEATH'
    END,
    m.level = MOD(r.runId,10) + 1,
    m.lastSavedAt = NOW() - INTERVAL (r.runId * 2) MINUTE,
    m.durationMinutes = CASE
        WHEN r.isRunning THEN 10 + r.runId
        ELSE 30 + (r.runId * 3)
    END;

-- =====================================================
-- WHITELIST
-- see_flop is already added automatically
-- by trigger addDefaultExplois
-- =====================================================

INSERT INTO Whitelist (userUuid, exploitID)
SELECT userUuid, 'change_to_random'
FROM Users

UNION ALL

SELECT userUuid, 'pick_other_player'
FROM Users

UNION ALL

SELECT userUuid, 'no_shuffle'
FROM Users;

-- =====================================================
-- EXPLOITS USED
-- =====================================================

INSERT INTO ExploitsUsed (runId, exploitID)
SELECT
    runId,
    CASE MOD(runId,4)
        WHEN 0 THEN 'see_flop'
        WHEN 1 THEN 'change_to_random'
        WHEN 2 THEN 'pick_other_player'
        ELSE 'no_shuffle'
    END
FROM Runs;
