DROP TRIGGER IF EXISTS trgRunsCalcEarnIns;
DELIMITER //
CREATE TRIGGER trgRunsCalcEarnIns
BEFORE INSERT ON Runs
FOR EACH ROW
BEGIN
    SET NEW.earnings = COALESCE(NEW.moneyTotal, 0) - COALESCE(NEW.moneySpend, 0);
END //
DELIMITER ;

DROP TRIGGER IF EXISTS trgRunsCalcEarnUpd;
DELIMITER //
CREATE TRIGGER trgRunsCalcEarnUpd
BEFORE UPDATE ON Runs
FOR EACH ROW
BEGIN
    SET NEW.earnings = COALESCE(NEW.moneyTotal, 0) - COALESCE(NEW.moneySpend, 0);
END //
DELIMITER ;

DROP TRIGGER IF EXISTS trgRunsSetStarted;
DELIMITER //
CREATE TRIGGER trgRunsSetStarted
AFTER INSERT ON Runs
FOR EACH ROW
BEGIN
    IF NEW.metadataID IS NOT NULL THEN
        UPDATE Metadata
        SET startedAt = CURRENT_TIMESTAMP
        WHERE metadataID = NEW.metadataID;
    END IF;
END //
DELIMITER ;

DROP TRIGGER IF EXISTS trgAddRunning;
DELIMITER //
CREATE TRIGGER trgAddRunning
AFTER INSERT ON Runs
FOR EACH ROW
BEGIN
    INSERT INTO Running (runID, data, sessionID)
    VALUES (NEW.runID, NULL, NULL);
END // 
DELIMITER ;

DROP TRIGGER IF EXISTS trgAddMetadata; 
DELIMITER //
CREATE TRIGGER trgAddMetadata
BEFORE INSERT ON Runs
FOR EACH ROW
BEGIN
    INSERT INTO Metadata () VALUES (); 
    SET NEW.metadataID = LAST_INSERT_ID();
END // 
DELIMITER ;

DROP TRIGGER IF EXISTS trgDeleteMetadata; 
DELIMITER //
CREATE TRIGGER trgDeleteMetadata
AFTER DELETE ON Runs
FOR EACH ROW
BEGIN
    DELETE FROM Metadata
    WHERE metadataID = OLD.metadataID;
END // 
DELIMITER ;

DROP TRIGGER IF EXISTS trgClearRunning; 
DELIMITER //
CREATE TRIGGER trgClearRunning
AFTER UPDATE ON Metadata
FOR EACH ROW
BEGIN
    IF NEW.typeEnd IS NOT NULL THEN
        DELETE Running
        WHERE runId = ( SELECT runID FROM Runs WHERE metadataID = NEW.metadataID ); 

        UPDATE Runs SET isRunning = FALSE
        WHERE metadataID = NEW.metadataID
    END IF;
END // 
DELIMITER ;
